name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - main  # срабатывает при пуше в ветку main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1. Проверка кода из репозитория
      - name: Checkout code
        uses: actions/checkout@v2

      # Шаг 2. Логин в Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Шаг 3. Сборка и пуш Docker образа на Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/kursach:latest
